/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contracts */
        get: operations["contracts_contracts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Knowledge Search */
        post: operations["knowledge_search_knowledge_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lifecycle/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transitions */
        get: operations["transitions_lifecycle_transitions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Configured read sources must answer before the API is reported ready.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reports */
        get: operations["list_reports_reports__kind__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{kind}/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_reports__kind___report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApiError
         * @description The error body of every status this API answers itself (400/404/422/500/502/503).
         *
         *     Includes the catch-all 500 of an unexpected exception, whose ``detail`` is always
         *     "internal server error" (no message, path or traceback).
         */
        ApiError: {
            /** Detail */
            detail: string;
        };
        /**
         * ContractNames
         * @description ``GET /contracts``: the registered contract model names, sorted.
         */
        ContractNames: string[];
        /**
         * EvidenceLevel
         * @description 知识条目的证据等级（docs/research/knowledge-base.md）。
         * @enum {string}
         */
        EvidenceLevel: "E0" | "E1" | "E2" | "E3" | "E4";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Health
         * @description Liveness (``/health`` and ``/healthz``) or readiness (``/readyz``) response.
         */
        Health: {
            /** Api Version */
            api_version: string;
            /** Status */
            status: string;
        };
        /**
         * InvalidReport
         * @description A report file the store found but could not serve: its ``id`` (file stem) and why.
         */
        InvalidReport: {
            /** Id */
            id: string;
            /** Reason */
            reason: string;
        };
        /**
         * JobList
         * @description ``GET /jobs``: every job in the order of its first start, plus the verified chain tip.
         */
        JobList: {
            /** Head Hash */
            head_hash: string;
            /** Jobs */
            jobs: components["schemas"]["JobView"][];
            /** Lines */
            lines: number;
        };
        /** @enum {string} */
        JobStatus: "succeeded" | "failed" | "interrupted";
        /**
         * JobView
         * @description One job of the worker's results journal (``apps.worker.jobs.JobRecord``), read-only.
         *
         *     ``status`` is ``succeeded``, ``failed`` or ``interrupted`` (started without a recorded result:
         *     running, or died and awaiting review / an idempotent re-run). ``attempts`` / ``result`` /
         *     ``error`` come from the ``job_result`` line and are ``null`` while interrupted.
         */
        JobView: {
            /** Attempts */
            attempts: number | null;
            /** Error */
            error: string | null;
            /** First Seq */
            first_seq: number;
            /** Job Id */
            job_id: string;
            /** Last Seq */
            last_seq: number;
            /** Name */
            name: string;
            /** Params */
            params: unknown;
            /** Reruns */
            reruns: number;
            /** Result */
            result: unknown;
            /** Starts */
            starts: number;
            status: components["schemas"]["JobStatus"];
        };
        /**
         * Kind
         * @description 可版本化对象的类型（02-domain.md §1）。
         * @enum {string}
         */
        Kind: "dataset" | "representation" | "feature" | "state" | "event" | "outcome" | "strategy" | "risk" | "cost_model" | "experiment" | "hypothesis" | "knowledge" | "artifact" | "profile" | "profile_selection_rule";
        /**
         * KnowledgeItem
         * @description 公开来源中的**待检验主张**，不是已验证结论。
         *
         *     `tags` / `assets`（ADR-0055，自 2.2.0）：主题标签与研究范围资产标识（资产类别或基础资产，
         *     **不是**交易所符号、上市记录或行情证据）；规范 token、严格升序、无重复；为空时不进入载荷。
         */
        KnowledgeItem: {
            /**
             * Assets
             * @default []
             */
            assets: string[];
            /** Claim */
            claim: string;
            /**
             * Conditions
             * @default []
             */
            conditions: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            evidence_level: components["schemas"]["EvidenceLevel"];
            /**
             * Kind
             * @default knowledge
             * @constant
             */
            kind: "knowledge";
            /** License */
            license: string;
            /**
             * Lineage
             * @default []
             */
            lineage: components["schemas"]["Ref"][];
            /**
             * Links
             * @default []
             */
            links: components["schemas"]["Ref"][];
            /** Name */
            name: string;
            /**
             * Schema Version
             * @default 2.5.0
             */
            schema_version: string;
            /** Source */
            source: string;
            /** @default unverified */
            status: components["schemas"]["KnowledgeStatus"];
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /** Version */
            version: string;
        };
        /**
         * KnowledgeQuery
         * @description 一次知识检索。
         *
         *     - `terms`：全部须出现在条目 `name` / `claim` / `conditions` 中（不区分大小写，AND 语义）；
         *     - `name_prefix`：库前缀，如 `strategy_`、`factor_`、`state_`（空 = 不限）；
         *     - `evidence_at_least`：只返回证据等级不低于该值的条目（空 = 不限）；
         *     - `statuses`：只返回这些状态（空 = 不限）；
         *     - `tags_all`（ADR-0055，自 2.2.0）：条目须包含**全部**这些标签（空 = 不限）；
         *     - `assets_any`（ADR-0055，自 2.2.0）：条目须至少包含其一，逐字精确相等（空 = 不限）；
         *     - `limit`：结果上限。
         *
         *     各过滤器之间为 AND；`tags_all` / `assets_any` 是规范 token、严格升序、无重复，为空时不进入载荷
         *     （同一信封版本下旧查询的 `query_hash` 逐位不变）。
         */
        KnowledgeQuery: {
            /**
             * Assets Any
             * @default []
             */
            assets_any: string[];
            evidence_at_least?: components["schemas"]["EvidenceLevel"] | null;
            /**
             * Limit
             * @default 50
             */
            limit: number;
            /**
             * Name Prefix
             * @default
             */
            name_prefix: string;
            /**
             * Schema Version
             * @default 2.5.0
             */
            schema_version: string;
            /**
             * Statuses
             * @default []
             */
            statuses: components["schemas"]["KnowledgeStatus"][];
            /**
             * Tags All
             * @default []
             */
            tags_all: string[];
            /**
             * Terms
             * @default []
             */
            terms: string[];
        };
        /**
         * KnowledgeResult
         * @description 一次检索的结果：条目按 `name`、`version` 规范排序；每条都有出处与许可。
         */
        KnowledgeResult: {
            /** Items */
            items: components["schemas"]["KnowledgeItem"][];
            /** Provider */
            provider: string;
            /** Query Hash */
            query_hash: string;
            /** Result Hash */
            result_hash: string;
            /**
             * Schema Version
             * @default 2.5.0
             */
            schema_version: string;
        };
        /**
         * KnowledgeStatus
         * @enum {string}
         */
        KnowledgeStatus: "unverified" | "supported" | "contradicted" | "inconclusive";
        /**
         * LifecycleTransition
         * @description One allowed lifecycle transition (``GET /lifecycle/transitions``), ``{"from", "to"}``.
         */
        LifecycleTransition: {
            /** From */
            from: string;
            /** To */
            to: string;
        };
        /**
         * Ref
         * @description 对象引用：`{kind}:{name}@{version}`。
         */
        Ref: {
            kind: components["schemas"]["Kind"];
            /** Name */
            name: string;
            /**
             * Schema Version
             * @default 2.5.0
             */
            schema_version: string;
            /** Version */
            version: string;
        };
        /**
         * ReportEnvelope
         * @description The minimal envelope every report kind is served through.
         */
        ReportEnvelope: {
            /** Content Hash */
            content_hash: string;
            /**
             * Created
             * Format: date-time
             */
            created: string;
            /** Id */
            id: string;
            kind: components["schemas"]["ReportKind"];
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
        /**
         * ReportKind
         * @description The report kinds the console serves ((a)-(d), Phase 9 gate calibration evidence, and the
         *     Phase 10 router stop / paper deviation, Phase 2 state diagnostics, Phase 3 event statistics,
         *     Phase 11 degradation checks, and Phase 8 retro audits).
         * @enum {string}
         */
        ReportKind: "validation_report" | "research_loop_round" | "state_strategy_matrix" | "router_paper_run" | "gate_calibration" | "router_stop" | "state_diagnostics" | "event_statistics" | "degradation_check" | "paper_deviation" | "retro_audit";
        /**
         * ReportListing
         * @description ``GET /reports/{kind}``: the well-formed reports (newest first) and every file skipped as
         *     malformed (by id), so a corrupt file is reported instead of silently dropped.
         */
        ReportListing: {
            /** Invalid */
            invalid: components["schemas"]["InvalidReport"][];
            kind: components["schemas"]["ReportKind"];
            /** Reports */
            reports: components["schemas"]["ReportEnvelope"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    contracts_contracts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractNames"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list_jobs_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobList"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    knowledge_search_knowledge_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    transitions_lifecycle_transitions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LifecycleTransition"][];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list_reports_reports__kind__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["schemas"]["ReportKind"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportListing"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    get_report_reports__kind___report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["schemas"]["ReportKind"];
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportEnvelope"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The report file is malformed or fails its kind's contract / identity check (ApiError), or the request is invalid (HTTPValidationError) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"] | components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
