/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contracts */
        get: operations["contracts_contracts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Knowledge Search */
        post: operations["knowledge_search_knowledge_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lifecycle/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transitions */
        get: operations["transitions_lifecycle_transitions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reports */
        get: operations["list_reports_reports__kind__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{kind}/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_reports__kind___report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * EvidenceLevel
         * @description 知识条目的证据等级（docs/research/knowledge-base.md）。
         * @enum {string}
         */
        EvidenceLevel: "E0" | "E1" | "E2" | "E3" | "E4";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * KnowledgeQuery
         * @description 一次知识检索。
         *
         *     - `terms`：全部须出现在条目 `name` / `claim` / `conditions` 中（不区分大小写，AND 语义）；
         *     - `name_prefix`：库前缀，如 `strategy_`、`factor_`、`state_`（空 = 不限）；
         *     - `evidence_at_least`：只返回证据等级不低于该值的条目（空 = 不限）；
         *     - `statuses`：只返回这些状态（空 = 不限）；
         *     - `limit`：结果上限。
         */
        KnowledgeQuery: {
            evidence_at_least?: components["schemas"]["EvidenceLevel"] | null;
            /**
             * Limit
             * @default 50
             */
            limit: number;
            /**
             * Name Prefix
             * @default
             */
            name_prefix: string;
            /**
             * Schema Version
             * @default 2.1.0
             */
            schema_version: string;
            /**
             * Statuses
             * @default []
             */
            statuses: components["schemas"]["KnowledgeStatus"][];
            /**
             * Terms
             * @default []
             */
            terms: string[];
        };
        /**
         * KnowledgeStatus
         * @enum {string}
         */
        KnowledgeStatus: "unverified" | "supported" | "contradicted" | "inconclusive";
        /**
         * ReportEnvelope
         * @description The minimal envelope every report kind is served through.
         */
        ReportEnvelope: {
            /** Content Hash */
            content_hash: string;
            /**
             * Created
             * Format: date-time
             */
            created: string;
            /** Id */
            id: string;
            kind: components["schemas"]["ReportKind"];
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
        /**
         * ReportKind
         * @description The report kinds the console serves ((a)-(d) plus Phase 9 gate calibration evidence).
         * @enum {string}
         */
        ReportKind: "validation_report" | "research_loop_round" | "state_strategy_matrix" | "router_paper_run" | "gate_calibration";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    contracts_contracts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    knowledge_search_knowledge_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transitions_lifecycle_transitions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    }[];
                };
            };
        };
    };
    list_reports_reports__kind__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["schemas"]["ReportKind"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportEnvelope"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_reports__kind___report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["schemas"]["ReportKind"];
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
