// Test helper (not a test file, not imported by the app): reads apps/web/fixtures/<kind>/*.json —
// report files generated by the real research/reports writers — as the envelopes apps/api serves.
import { readdirSync, readFileSync } from "node:fs";
import type { ReportEnvelope, ReportKind } from "../api";

const FIXTURES = new URL("../../fixtures/", import.meta.url);

export function fixtureEnvelopes(kind: ReportKind): ReportEnvelope[] {
  const directory = new URL(`${kind}/`, FIXTURES);
  return readdirSync(directory)
    .filter((name) => name.endsWith(".json"))
    .sort()
    .map((name) => ({
      kind,
      id: name.slice(0, -".json".length),
      created: "2026-09-26T00:00:00Z",
      content_hash: "0".repeat(64),
      payload: JSON.parse(readFileSync(new URL(name, directory), "utf-8")) as Record<string, unknown>,
    }));
}

/** A deep copy, so a test can edit a fixture payload without touching the others. */
export function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}
